# Conclusion

In our project, we comprehensively analyze and visualize crime incidents in New York City from 2013 to 2021 from multiple perspectives such as magnitude, time, type, age, sex, position and so on. Besides, we also try to explore the connection between crime and other social factors such as COVID-19 VS hate crimes and Mental Health Service VS Drugs&Gun Crimes. Here are some conclusions and further suggestions:

In terms of the overall crime situation in New York, the total number of crimes in New York City has been declining sharply every year from 2011-2021. Among all types, the proportion of DANGEROUS DRUGS is constantly decreasing, the proportion of ASSAULT 3 is constantly increasing. Among 5 boroughs, proportion of crime in Queens and Staten Island is increasing especially after 2015 so we should pay more attention on it.



Besides, as for covid-19, 




What's more, as for mental health services, health centers are positively correlated with the number of crimes in borough level and the location of the mental health center is very consistent with the distribution of drug crime and weapon crime’s sites on map views. We can conclude NYC's mental health construction is now quite complete and supportive but we can add some mental health service centers in Rockaway Beach and the area around EAST NEW YORK in Brooklyn according to the crime situation.