--- 
title: "EDAV of Crime in NYC from 2013 to 2021"
author: "Pengyu Zou, Siyu Li, Nuanyu Shou"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

New York is one of the most developed cities in the world. The safety of this city is closely related to millions of New Yorkers. 

In this project, we visualize crime incidents in New York City from 2006 to 2021 from multiple perspectives such as total numbers, crime types, location, genders, ages, case levels and time. At the same time, we analyze factors that may be related to the crime rate in New York City.

Besides, As the COVID-19 has had a huge impact on the entire human society, we also explore how the COVID-19 epidemic affects the hate crime condition in New York City since we speculate that if the epidemic will increase prejudice between races.

What's more, drug abuse and weapons crime are related to mental health to a certain extent. we'll try to explore the relationship between the level of mental health services and these crimes.

From these three aspects, we will perform analysis and give some suggestions.
